reads: SRR2960981

# Estimation of read error rate (recommended 0.01 for Illumina)
error_rate: 0.01

# Pipeline will approximate coverage of reads, which may be too high to manage in memory.
# If so, a Snakemake rule will downsample the reads to this coverage (recommended 42).
max_coverage: 42

# Genome filename
genome: "Zea_mays.AGPv4.fa"
# Approximate genome size
genome_size: 2500000000

# K-mer size (recommended 17)
mer_size: 17

binsize: 1000000

# Which sequences from the genome would you like to design oligos for?
sequences:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10

subsampling:
  # Number of threads to use for checking coverage and subsampling if necessary
  threads: 15
jellyfish:
  # Number of threads to use for counting with jellyfish
  threads: 15
mapping:
  # Number of threads to use for mapping with bwa
  threads: 16
