# This config is for Arabidopsis thaliana.

# Accession of reads to download from NCBI SRA,
# or name of reads file (without .fastq.gz) located in data/reads/.
reads: ERR2929052

# Genome filename
genome: "TAIR10_chr_all.fas"
# Optional: URL to download genome
genome_download: https://www.arabidopsis.org/download_files/Genes/TAIR10_genome_release/TAIR10_chromosome_files/TAIR10_chr_all.fas

# Approximate genome size
genome_size: 135000000
# Bin size for probe coverage plot
binsize: 1000000

# Which sequences from the genome would you like to design oligos for?
sequences:
  - 1
  - 2
  - 3
  - 4
  - 5

# K-mer size (recommended 17)
kmer_size: 17
# Probe size (recommended 45)
oligo_size: 45
# Distance between start of consecutive oligos (recommended 3)
step_size: 3

bed_regions:
  - example.bed

fastq_dump:
  # Number of threads to use for dumping fastq from SRA
  threads: 4
subsampling:
  # Number of threads to use for checking coverage and subsampling if necessary
  threads: 20
  # Pipeline will approximate coverage of reads, which may be too high to manage in memory.
  # If so, a Snakemake rule will downsample the reads to this coverage (recommended 42).
  max_coverage: 60
  # Seed to use for subsampling
  seed: 85
jellyfish:
  # Number of threads to use for counting with jellyfish
  threads: 20
  # Estimation of sequencing error rate in reads.
  # Required by Jellyfish to calculate hash size.
  # (Recommended 0.01 for Illumina sequencing)
  error_rate: 0.01
oligo_filtering:
  # Maximum number of consecutive identical bases
  max_homopolymer: 5
  primer3:
    # Minimum melting temperature for oligos (primer3)
    min_tm: 37
    # Maximum hairpin melting temperature for oligos (primer3)
    max_htm: 35
    # Minimum difference between melting temperature and hairpin melting temperature (primer3)
    min_dtm: 10
mapping:
  # Number of threads to use for mapping with bwa
  threads: 2
