name: michelangelo
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bedtools=2.28.0
  - bwa=0.7.17
  - graphviz=2.38.0
  - jellyfish=2.2.10
  - python=3.7.3
  - r-base=3.6.0
  - r-dplyr=0.8.3
  - r-ggplot2=3.2.0
  - sra-tools=2.9.6
  - samtools=1.9
  - seqtk=1.3
  - snakemake=5.4.5
