name: davinci
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bedtools=2.28.0
  - bwa=0.7.17
  - graphviz=2.40.1
  - jellyfish=2.2.10
  - pigz=2.4
  - primer3-py=0.5.4
  - python=3.7.3
  - r-base=3.6.1
  - r-dplyr=0.8.3
  - r-ggplot2=3.2.0
  - r-readr=1.3.1
  - sra-tools=2.9.6
  - samtools=1.9
  - seqtk=1.3
  - snakemake=5.4.5
  - unzip=6.0
  - wget=1.20.1
  - vim=8.1.1343
